name: fluttertagger
description: A Flutter package that allows for the extension of TextFields to provide tagging capabilities (user mentions, hashtags, etc).
version: 2.3.0
repository: https://github.com/Crazelu/fluttertagger
issue_tracker: https://github.com/Crazelu/fluttertagger/issues
topics: [user, mention, hashtag, tagging]

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
