name: fluttertagger
description: A Flutter package that allows for the extension of TextFields to provide tagging capabilities.
version: 1.0.0
repository: https://github.com/Crazelu/fluttertagger

environment:
  sdk: ">=2.17.1 <=3.0.3"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

